In [ ]:
https://blog.csdn.net/qq_32458499/article/details/78856530
https://blog.csdn.net/feixiang7701/article/details/81611356
# 四种迭代器
# https://www.jianshu.com/p/5f9aca0a14fb

In [ ]:
import numpy as np
import tensorflow as tf

# 固定长度

# input_x = [np.asarray([1,2,3]), np.asarray([4,5]),[6], [7,8], [9]]
input_x = [[1,2,3],[4,5,6],[7,8,9]]
# input_x = np.asarray(input_x)
# input_x = np.asarray(range(0, 18))
input_y = input_x

data_loader = tf.data.Dataset.from_tensor_slices(
    {'text': np.asarray(input_x),
     'label': np.asarray(input_y)}).batch(2)

session = tf.Session()

iterator = data_loader.make_one_shot_iterator()
one_element = iterator.get_next()

while True:
    try:
        sample_batched = session.run(one_element)
        inputs = sample_batched['text']
        labels = sample_batched['label']
        print(">>> inputs", inputs)
        print(">>> labels", labels)
    except tf.errors.OutOfRangeError:
        break

In [30]:
import numpy as np
import tensorflow as tf

# 变长

# input_x = [np.asarray([1,2,3]), np.asarray([4,5]),[6], [7,8], [9]]
input_x = [[1,2],[4,5,6],[7,8,9]]
# input_x = np.asarray(input_x)
# input_x = np.asarray(range(0, 18))
input_y = input_x

data_loader = tf.data.Dataset.from_tensor_slices(
    {'text': np.asarray(input_x),
     'label': np.asarray(input_y)}).batch(2)

session = tf.Session()

iterator = data_loader.make_one_shot_iterator()
one_element = iterator.get_next()

while True:
    try:
        sample_batched = session.run(one_element)
        inputs = sample_batched['text']
        labels = sample_batched['label']
        print(">>> inputs", inputs)
        print(">>> labels", labels)
    except tf.errors.OutOfRangeError:
        break


TypeError: Expected binary or unicode string, got [1, 2]

In [13]:
import numpy as np
import tensorflow as tf

input_x = np.asarray(range(0, 180)).reshape(10,6,3)

print(type(input_x))
print(type(input_x[0]))
print(type(input_x[0][0]))

input_y = input_x

data_loader = tf.data.Dataset.from_tensor_slices(
    {'text': np.asarray(input_x),
     'label': np.asarray(input_y)}).batch(8)

session = tf.Session()

iterator = data_loader.make_one_shot_iterator()
one_element = iterator.get_next()

while True:
    try:
        sample_batched = session.run(one_element)
        inputs = sample_batched['text']
        labels = sample_batched['label']
        print(">>> inputs", inputs)
        print(">>> labels", labels)
    except tf.errors.OutOfRangeError:
        break

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
>>> inputs [[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]]

 [[ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]
  [ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]]

 [[ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]]

 [[ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]]

 [[108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]]

 [[126 127 128]
  [129 130 131]
  [132 133 134]
  [135 136 137]
  [138 139 140]
  [141 142 143]]]
>>> labels [[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  

In [17]:
a = [1, 2, 3]
b = [a, a, a]
print(b)
print(type(b))
print(type(np.asarray(b)))
print(type(b))
print(type(b[0]))
print(type(b[0][0]))

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>
<class 'int'>


In [24]:
a = [1, 2, 3]
b = [a, a, a]
print(b)
print(type(b))
print(type(np.array(b)))
c = np.array(b)
print(type(b))
print(type(b[0]))
print(type(b[0][0]))
print(type(c))
print(type(c[0]))
print(type(c[0][0]))

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [25]:
a = [1, 2, 3]
b = [a, a, a]
print(b)
print(type(b))
print(type(np.asarray(b)))
c = np.asarray(b)
print(type(b))
print(type(b[0]))
print(type(b[0][0]))
print(type(c))
print(type(c[0]))
print(type(c[0][0]))

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
