In [1]:
import tensorflow as tf
import numpy as np

dataset = tf.data.Dataset.from_tensor_slices(np.array([1.0, 2.0, 3.0, 4.0, 5.0]))

In [2]:
print(dataset)

<TensorSliceDataset shapes: (), types: tf.float64>


In [19]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1.0, 2.0, 3.0, 4.0, 5.0]))
dataset = dataset.map(lambda x: x + 1) # 2.0, 3.0, 4.0, 5.0, 6.0
dataset = dataset.batch(2)

iterator = dataset.make_one_shot_iterator()
one_element = iterator.get_next()
with tf.Session() as sess:
    print(sess.run(one_element))

[2. 3.]


In [4]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1.0, 2.0, 3.0, 4.0, 5.0]))
iterator = dataset.make_one_shot_iterator()
one_element = iterator.get_next()
with tf.Session() as sess:
    try:
        while True:
            print(sess.run(one_element))
    except tf.errors.OutOfRangeError:
        print("end!")

1.0
2.0
3.0
4.0
5.0
end!


In [29]:
list_a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
list_b = np.array([[1, 2], [3, 4], [5,6], [7,8], [9,9]])
list_label = list_b

dataset = tf.data.Dataset.from_tensor_slices({'a':list_a, 'b':list_b, 'label':list_label})
dataset = dataset.batch(2)

iterator = dataset.make_one_shot_iterator()

with tf.Session() as sess:
    while True:
        try:
            print(sess.run(iterator.get_next()))
        except tf.errors.OutOfRangeError:
            break

{'a': array([1., 2.]), 'b': array([[1, 2],
       [3, 4]]), 'label': array([[1, 2],
       [3, 4]])}
{'a': array([3., 4.]), 'b': array([[5, 6],
       [7, 8]]), 'label': array([[5, 6],
       [7, 8]])}
{'a': array([5.]), 'b': array([[9, 9]]), 'label': array([[9, 9]])}


In [27]:
list_a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
list_b = np.array([[1, 2], [3, 4], [5,6], [7,8], [9,9]])

dataset = tf.data.Dataset.from_tensor_slices((list_b, list_a))
dataset = dataset.batch(2)

iterator = dataset.make_one_shot_iterator()

with tf.Session() as sess:
    while True:
        try:
            print(sess.run(iterator.get_next()))
        except tf.errors.OutOfRangeError:
            break

(array([[1, 2],
       [3, 4]]), array([1., 2.]))
(array([[5, 6],
       [7, 8]]), array([3., 4.]))
(array([[9, 9]]), array([5.]))
