In [ ]:
# reduce 相关函数主要用于降维
# reduce_max
# reduce_mean
# reduce_sum
# reduce_min
# reduce_prod

In [25]:
import tensorflow as tf
import numpy as np

init_a = np.array(range(24)).reshape(2,3,4)
# print(init_a)

a = tf.Variable(initial_value=init_a, dtype=tf.float64)
#W = tf.Variable(tf.zeros([3, 10]), dtype=float, name="weight")
init=tf.global_variables_initializer()

r_max_0 = tf.reduce_max(a, 0)
r_max_1 = tf.reduce_max(a, 1)
r_max_2 = tf.reduce_max(a, 2)

r_prod_0 = tf.reduce_prod(a, 0)
r_prod_1 = tf.reduce_prod(a, 1)
r_prod_2 = tf.reduce_prod(a, 2)

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(a))
    print(sess.run(r_max_0))
    print(sess.run(r_max_1))
    print(sess.run(r_max_2))
    
    print(sess.run(r_prod_0))
    print(sess.run(r_prod_1))
    print(sess.run(r_prod_2))

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[ 8.  9. 10. 11.]
 [20. 21. 22. 23.]]
[[ 3.  7. 11.]
 [15. 19. 23.]]
[[  0.  13.  28.  45.]
 [ 64.  85. 108. 133.]
 [160. 189. 220. 253.]]
[[   0.   45.  120.  231.]
 [3840. 4641. 5544. 6555.]]
[[     0.    840.   7920.]
 [ 32760.  93024. 212520.]]
