In [1]:
import tensorflow as tf 


In [24]:
a = list(range(9))
b = list(map(lambda x:x[0] + x[1], zip(a, a)))
matrix_a = tf.reshape(a, [3,3])
matrix_b = tf.reshape(b, [3,3])

sess = tf.Session()
print(sess.run(matrix_a))
print(sess.run(matrix_b))
print(sess.run(matrix_a*matrix_b))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[  0   2   8]
 [ 18  32  50]
 [ 72  98 128]]


In [10]:
print(type(range(8)))

print(list(range(9)))

<class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [11]:
for item in range(8):
    print(item)

0
1
2
3
4
5
6
7
