In [1]:
import numpy as np

In [2]:
a = [[[1],[2],[3],[4]],[[5],[6],[7],[8]],[[9],[10],[11],[12]]]
print(a)

[[[1], [2], [3], [4]], [[5], [6], [7], [8]], [[9], [10], [11], [12]]]


In [3]:
print(np.mean(a))

6.5


In [4]:
print(np.mean(a, axis=0))

[[5.]
 [6.]
 [7.]
 [8.]]


In [5]:
print(np.mean(a, axis=1))

[[ 2.5]
 [ 6.5]
 [10.5]]


In [15]:
b = np.arange(1,28,1)
print(b)
b=b.reshape(3,3,3)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [16]:
print(np.mean(b, axis=0))

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [17]:
print(np.mean(b, axis=1))

[[ 4.  5.  6.]
 [13. 14. 15.]
 [22. 23. 24.]]
