In [3]:
import numpy as np

matrix = np.random.rand(6,3)
print(matrix)

[[0.30983564 0.06400809 0.21519437]
 [0.21491848 0.25523354 0.32270796]
 [0.21792866 0.08834384 0.60826659]
 [0.62430878 0.65431505 0.02946159]
 [0.93487411 0.62631512 0.61672987]
 [0.40281301 0.63700852 0.27089114]]


In [19]:
# 第一行 
[print(tmp) for tmp in matrix[0]]

0.3098356411999731
0.06400809174194588
0.21519436744867004


[None, None, None]

In [17]:
# matrix to list
list_1 = matrix.tolist()

[print(tmp) for tmp in list_1]

[0.3098356411999731, 0.06400809174194588, 0.21519436744867004]
[0.2149184831253812, 0.25523354308259694, 0.3227079567794877]
[0.2179286606081351, 0.08834384370544524, 0.6082665869251934]
[0.6243087765961715, 0.6543150527110951, 0.029461587525002608]
[0.934874111072087, 0.6263151233038557, 0.6167298690413371]
[0.40281300596809755, 0.6370085154294345, 0.270891142234285]


[None, None, None, None, None, None]

In [16]:
[print(tmp) for tmp in matrix[1:]]

[0.21491848 0.25523354 0.32270796]
[0.21792866 0.08834384 0.60826659]
[0.62430878 0.65431505 0.02946159]
[0.93487411 0.62631512 0.61672987]
[0.40281301 0.63700852 0.27089114]


[None, None, None, None, None]

In [20]:
# 获取每行的最大数的下标
list_1 = matrix.tolist()
list_max_index = [np.argmax(i) for i in list_1]
print(list_max_index)

[0, 2, 2, 1, 0, 1]
