In [9]:
list1 = [item for item in range(0,10,1)]
print(list1)
print(type(list1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [10]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [20]:
list2 = [a, a, a]
print(type(list2))
print(list2[1].shape)

list2 = np.array(list2)
print(list2.shape)
print(type(list2))
print(type(list2[1]))

<class 'list'>
(3, 5)
(3, 3, 5)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
list1 = [1,2,3]

list2 = [list1, list1, list1]

np1 = np.array(list2)

print(type(list1))
print(type(list2))
print(type(np1))
print(type(np1[1]))
print(type(np1[1][1]))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
