In [1]:
import numpy as np
import tensorflow as tf
from keras import backend as K

/opt/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
tmp1 = np.random.rand(29,64)
print(tmp1)

[[0.12793736 0.3268349  0.78945311 ... 0.98737659 0.91560323 0.7843952 ]
 [0.99765738 0.74526095 0.38011578 ... 0.39919284 0.94963937 0.48160416]
 [0.71010706 0.43960214 0.16159297 ... 0.38539073 0.77627271 0.00161811]
 ...
 [0.0117222  0.55856517 0.25315168 ... 0.56359115 0.19223121 0.75421679]
 [0.01346155 0.60562863 0.66317539 ... 0.96764798 0.50800696 0.4789311 ]
 [0.13408003 0.16861855 0.85839206 ... 0.68637963 0.09690947 0.25567711]]


In [3]:
tmp2 = np.random.rand(64,16)
print(tmp2)

[[0.84360929 0.63837608 0.13242223 ... 0.08965332 0.14560372 0.58414268]
 [0.47331872 0.23805275 0.51649913 ... 0.85952129 0.70501862 0.46922832]
 [0.60174652 0.75402798 0.97149023 ... 0.05694413 0.84745101 0.63808852]
 ...
 [0.50618852 0.23996977 0.72436008 ... 0.71091915 0.03509334 0.96031477]
 [0.83787697 0.26851698 0.85624518 ... 0.89341237 0.71928426 0.69467505]
 [0.96423299 0.6681948  0.36390453 ... 0.94757173 0.20670912 0.38269334]]


In [4]:
tmp3 = np.random.rand(16,1)
print(tmp3)

[[0.22402317]
 [0.36888819]
 [0.60474145]
 [0.68360417]
 [0.30743374]
 [0.2033141 ]
 [0.17295243]
 [0.20104269]
 [0.91232157]
 [0.81443798]
 [0.06060369]
 [0.32957842]
 [0.54942952]
 [0.87331486]
 [0.5899956 ]
 [0.16892577]]


In [6]:
tmp4 = np.dot(tmp1,tmp2)
print(tmp4)

[[17.81159819 17.39006283 18.48386889 16.36524456 16.47966852 16.17233606
  18.34783773 17.5462659  15.41928726 18.57694806 17.46696827 17.47827332
  18.98050703 19.62561559 15.54310786 19.11054841]
 [16.59198034 17.08332393 17.9638746  16.37698043 14.54281991 16.21080602
  16.27987236 15.7741949  16.23273113 17.60286905 15.31720971 16.29251441
  18.15462997 17.14858158 15.4743623  17.31880809]
 [15.5830147  15.13257125 15.85817537 15.69079613 14.13786357 15.82791323
  15.49529318 14.24538639 14.38940042 15.91317536 14.23083763 14.61268518
  15.68857558 17.28520232 15.21910834 16.06477551]
 [15.81706546 16.55633554 15.93641535 14.73141446 13.68109199 14.69501026
  16.01947627 15.90044457 15.02441626 17.23777816 14.8906053  15.20535738
  15.99438075 17.72085542 15.84853252 17.55011279]
 [14.71809117 15.63888673 15.76389497 14.16906927 14.0244527  14.54553245
  16.53985897 14.5298495  14.48299514 16.91874206 14.52601251 15.81194462
  15.79728775 15.09732236 15.29243773 16.71136839]
 [16.

In [9]:
tmp5 = np.dot(tmp4,tmp3)
print(tmp5)

[[123.80839918]
 [118.28152112]
 [109.67262035]
 [112.75858634]
 [108.12962488]
 [112.27205506]
 [119.08290805]
 [120.62332297]
 [ 93.4702101 ]
 [111.03797132]
 [105.78004878]
 [ 96.14017765]
 [121.78185959]
 [117.75024708]
 [105.82969984]
 [126.56376488]
 [122.31716032]
 [110.86219712]
 [111.56352842]
 [119.4088447 ]
 [ 93.35237778]
 [ 99.09814125]
 [110.11455279]
 [109.58980723]
 [105.79468764]
 [107.13998189]
 [100.03724554]
 [110.46722769]
 [ 99.92804394]]
